# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XOneTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'R.swift', '~> 5'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'
pod 'FirebaseDatabase'
pod 'Firebase/Firestore'
pod 'FirebaseStorage'
pod 'Kingfisher'

  # Pods for XOneTask

end
